---
# tasks file for xfsprogs

- name: install xfsprogs
  become: yes
  apt:
    update_cache: yes
    install_recommends: no
    cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
    state: latest
    name: xfsprogs
  tags: xfsprogs
